---
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-heketi
  namespace: default
spec:
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
           {"key":"CriticalAddonsOnly", "operator":"Exists"}]
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "heketi/heketi:dev",
            "imagePullPolicy": "IfNotPresent",
            "command": [ "bash", "/opt/bin/provision" ],
            "env": [
              {
                "name": "HEKETI_CLI_SERVER",
                "value": "http://deploy-heketi:8080"
              },
              {
                "name": "NODE_DEVICES_PATTERN",
                "value": "/dev/[sv]d[bc]"
              }
            ],
            "volumeMounts": [
              {
                "mountPath": "/var/heketi/manifests",
                "name": "heketi-storage-manifests"
              },
              {
                "mountPath": "/dev",
                "name": "dev"
              },
              {
                "mountPath": "/opt/bin",
                "name": "heketi-topology"
              }
            ]
          }
        ]'
    spec:
      restartPolicy: Never
      containers:
      - image: gcr.io/google_containers/hyperkube-amd64:v1.5.1
        name: hyperkube
        command:
          - "bash"
          - "/opt/bin/deploy-heketi"
        volumeMounts:
          - mountPath: /opt/bin
            name: deploy-heketi
          - mountPath: /var/heketi/manifests
            name: heketi-storage-manifests
          - mountPath: /srv/asset/manifests
            name: srv-asset-manifests
      volumes:
        - name: deploy-heketi
          configMap:
            name: deploy-heketi
        - name: heketi-storage-manifests
          emptyDir: {}
        - name: heketi-topology
          configMap:
            name: heketi-topology
        - name: srv-asset-manifests
          hostPath:
            path: /srv/asset/manifests
        - name: dev
          hostPath:
            path: /dev
