---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-heketi
data:
  deploy-heketi: |-
    #!/bin/bash -e

    # while [ ! -f /var/heketi/manifests/heketi-storage.json ]
    # do
    #   sleep 2
    #   echo -n "waiting for '/var/heketi/manifests/heketi-storage.json'"
    # done
    # while true; do sleep 2; done
    /hyperkube kubectl apply -f /var/heketi/manifests/heketi-storage.json
    /hyperkube kubectl delete all,service,jobs,deployment,secret --selector="deploy-heketi"
    /hyperkube kubectl apply -f /opt/bin/heketi-deployment.yaml

  heketi-deployment.yaml: |-
    ---
    kind: Service
    apiVersion: v1
    metadata:
      name: heketi
      labels:
        glusterfs: heketi-service
        deploy-heketi: support
      annotations:
        description: Exposes Heketi Service
    spec:
      selector:
        name: heketi
      ports:
      - name: heketi
        port: 8080
        targetPort: 8080
    ---
    kind: Deployment
    apiVersion: extensions/v1beta1
    metadata:
      name: heketi
      labels:
        glusterfs: heketi-deployment
      annotations:
        description: Defines how to deploy Heketi
    spec:
      replicas: 1
      template:
        metadata:
          name: heketi
          labels:
            name: heketi
            glusterfs: heketi-pod
        spec:
          serviceAccountName: heketi-service-account
          containers:
          - image: heketi/heketi:dev
            imagePullPolicy: Always
            name: heketi
            env:
            - name: HEKETI_EXECUTOR
              value: kubernetes
            - name: HEKETI_KUBE_USE_SECRET
              value: "y"
            - name: HEKETI_FSTAB
              value: "/var/lib/heketi/fstab"
            - name: HEKETI_SNAPSHOT_LIMIT
              value: '14'
            - name: HEKETI_KUBE_GLUSTER_DAEMONSET
              value: "y"
            ports:
            - containerPort: 8080
            volumeMounts:
            - name: db
              mountPath: "/var/lib/heketi"
            readinessProbe:
              timeoutSeconds: 3
              initialDelaySeconds: 3
              httpGet:
                path: "/hello"
                port: 8080
            livenessProbe:
              timeoutSeconds: 3
              initialDelaySeconds: 30
              httpGet:
                path: "/hello"
                port: 8080
          volumes:
          - name: db
            glusterfs:
              endpoints: heketi-storage-endpoints
              path: heketidbstorage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heketi-topology
data:
  provision: |-
    #!/bin/bash
    KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)

    function gluster_readiness {
      curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/pods?labelSelector=glusterfs-node=pod > /tmp/gluster_pods.json 2>&1
      echo $(python3 - <<EOF
    import sys
    import json

    if __name__ == '__main__':
        json_raw = json.loads(open('/tmp/gluster_pods.json').read())
        pods = list((x for x in json_raw['items'] if x['status']['containerStatuses'][0]['ready'] == True))
        sys.exit(int(len(pods) < 3))
    EOF
    )
    }

    c=`gluster_readiness`
    until [ "$c" -ge 3 ]
    do
      c=`gluster_readiness`
      echo -ne "$((3 - c)) glusterfs pod left to run.."\\r
      sleep 3
    done

    function create_topology {
      curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/nodes?labelSelector=storagenode=glusterfs > /tmp/nodes.json 2>&1

      echo $(python3 - <<END
    import sys
    import json
    import argparse
    import os

    raw = json.loads(open('/tmp/nodes.json','r').read())

    def getAddrWithType(dic, t):
        return next((x for x in dic['status']['addresses'] if x['type'] == t))['address']

    if __name__ == '__main__':
        devices = $NODE_DEVICES
        topo = { 'clusters': [ { 'nodes': [] } ] }

        for item in raw['items']:
          ipv4 = getAddrWithType(item, 'LegacyHostIP')
          hostname = getAddrWithType(item, 'Hostname')
          node = {
            'node': {
              'hostnames': {
          'manage' : [ ipv4 ] ,
          'storage': [ hostname ]
              },
              'zone': 1
            },
           'devices': devices
          }
          topo['clusters'][0]['nodes'].append(node)

        print(json.dumps(topo))
        sys.exit(int(len(raw['items']) < 3))

    END
      ) > /topology.json
    }

    until create_topology
    do
      echo -ne "retry create topology .."
    done

    heketi-cli topology load --json=/topology.json 
    sleep 10

    result=`heketi-cli setup-openshift-heketi-storage 2>&1`
    echo $result
    if echo $result | grep -q "Error.*Volume.*heketidbstorage alreay exists"; then
      exit 0
    fi
    cp -fv /heketi-storage.json /var/heketi/manifests/
