#!/bin/bash
mkdir -p manifests
cat deploy-heketi-configMap.yaml > manifests/deploy-heketi.yaml
cat heketi-service-account.yaml \
	glusterfs-daemonset.yaml \
	deploy-heketi-deployment.yaml \
	configure-heketi-job.yaml >> manifests/deploy-heketi.yaml
