#!/bin/bash
manifests_dir=manifests/glusterfs
rm -fvr $manifests_dir
mkdir -p $manifests_dir
cp deploy-heketi-configMap.yaml $manifests_dir/configure-heketi.yaml
cat configure-heketi-job.yaml >> $manifests_dir/configure-heketi.yaml

cp glusterfs-daemonset.yaml $manifests_dir
cp heketi-service-account.yaml $manifests_dir
cp deploy-heketi-deployment.yaml $manifests_dir
