#!/bin/bash
mkdir -p manifests
rm -fv manifests/*
cp deploy-heketi-configMap.yaml manifests/configure-heketi.yaml
cat configure-heketi-job.yaml >> manifests/configure-heketi.yaml

cp glusterfs-daemonset.yaml manifests/
cp heketi-service-account.yaml manifests/
cp deploy-heketi-deployment.yaml manifests/
